name: Docker Hub API Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Build Docker Image
        run: |
          docker build -t emmylong1/simple-time-api:v1 .
        env:
          DOCKER_BUILDKIT: 1  # Enable Docker BuildKit for improved build performance

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push emmylong1/simple-time-api:v1
