name: GCP API Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-api:tag .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-api:tag

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
